---
- name: Install PHP 5.6 modules
# Note: Some of the package names fail check mode if the Ondrej repo hasn't yet been installed.
  apt:
    name: "{{ php56_modules }}"
    update_cache: yes
    state: present

- name: ensure php5.6-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php5.6-fpm

- name: increase php5.6-fpm memory_limit
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^(.*)memory_limit(.*)=(.*)'
    line: 'memory_limit = {{ php_memory_limit }}'
  notify:
    - restart php5.6-fpm

- name: increase php5.6-fpm max_input_vars
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^(.*)max_input_vars(.*)=(.*)'
    line: 'max_input_vars = {{ php_max_input_vars }}'
  notify:
    - restart php5.6-fpm

- name: enable mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/5.6/cli/conf.d/20-mcrypt.ini

- name: Ensure php5.6-fpm is started.
  service: name=php5.6-fpm state=started
