---
- name: Install PHP 7.1 modules
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - php7.1-common
    - php7.1-bcmath
    - php7.1-curl
    - php7.1-fpm
    - php7.1-gd
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-opcache
    - php7.1-soap
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-zip

- name: ensure php7.1-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php7.1-fpm

- name: increase php7.1-fpm memory_limit
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)memory_limit(.*)=(.*)'
    line: 'memory_limit = {{ php_memory_limit }}'
  notify:
    - restart php7.1-fpm

- name: increase php7.1-fpm max_input_vars
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)max_input_vars(.*)=(.*)'
    line: 'max_input_vars = {{ php_max_input_vars }}'
  notify:
    - restart php7.1-fpm

- name: Ensure php7.1-fpm is started.
  service: name=php7.1-fpm state=started

- name: Set default PHP version to {{ php_default_version }} (PHP CLI)
  shell: update-alternatives --set php /usr/bin/php{{ php_default_version }}
  
- name: Check for existence of /etc/acro/add-website.conf
  stat: path=/etc/acro/add-website.conf.php{{ php_default_version }}
  register: add_website_conf
  tags:
    - acroutils
  
- name: Set default PHP version to {{ php_default_version }} (acro-add-website.sh)
  file:
    state: link
    src: /etc/acro/add-website.conf.php{{ php_default_version }}
    dest: /etc/acro/add-website.conf
  when: add_website_conf.stat.exists == true
  tags:
    - acroutils
