---
- name: Install PHP 7.1 modules
# Note: Some of the package names fail check mode if the Ondrej repo hasn't yet been installed.
  apt:
    name:
    - php7.1-common
    - php7.1-bcmath
    - php7.1-curl
    - php7.1-fpm
    - php7.1-gd
    - php7.1-igbinary
    - php7.1-mbstring
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-pgsql
    - php7.1-oauth
    - php7.1-opcache
    - php7.1-redis
    - php7.1-soap
    - php7.1-xml
    - php7.1-xmlrpc
    - php7.1-zip
    update_cache: yes
    state: present

- name: ensure php7.1-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php7.1-fpm

- name: increase php7.1-fpm memory_limit
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)memory_limit(.*)=(.*)'
    line: 'memory_limit = {{ php_memory_limit }}'
  notify:
    - restart php7.1-fpm

- name: increase php7.1-fpm max_input_vars
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^(.*)max_input_vars(.*)=(.*)'
    line: 'max_input_vars = {{ php_max_input_vars }}'
  notify:
    - restart php7.1-fpm

- name: enable mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/7.1/cli/conf.d/20-mcrypt.ini

- name: Ensure php7.1-fpm is started.
  service: name=php7.1-fpm state=started
