---
- name: Install PHP 7.0 modules
# Note: Some of the package names fail check mode if the Ondrej repo hasn't yet been installed.
  apt:
    name:
    - php7.0-common
    - php7.0-bcmath
    - php7.0-curl
    - php7.0-fpm
    - php7.0-gd
    - php7.0-igbinary
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-pgsql
    - php7.0-oauth
    - php7.0-opcache
    - php7.0-redis
    - php7.0-soap
    - php7.0-xml
    - php7.0-xmlrpc
    - php7.0-zip
    update_cache: yes
    state: present

- name: ensure php7.0-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php7.0-fpm

- name: increase php7.0-fpm memory_limit
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^(.*)memory_limit(.*)=(.*)'
    line: 'memory_limit = {{ php_memory_limit }}'
  notify:
    - restart php7.0-fpm

- name: increase php7.0-fpm max_input_vars
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^(.*)max_input_vars(.*)=(.*)'
    line: 'max_input_vars = {{ php_max_input_vars }}'
  notify:
    - restart php7.0-fpm

- name: enable mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/7.0/cli/conf.d/20-mcrypt.ini

- name: Ensure php7.0-fpm is started.
  service: name=php7.0-fpm state=started
