---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: '600'
      changed_when: false

  roles:
    - role: ansible-role-php

  vars:
    php_default_version: 7.2
    php_memory_limit: 192M
    php_max_input_vars: 100
    php_versions:
      - 7.1
      - 7.2
