---
- name: restart php5.6-fpm
  service: name=php5.6-fpm state=restarted

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted

- name: restart php7.1-fpm
  service: name=php7.1-fpm state=restarted

- name: restart php7.2-fpm
  service: name=php7.2-fpm state=restarted

- name: restart php7.3-fpm
  service: name=php7.3-fpm state=restarted

- name: restart php7.4-fpm
  service: name=php7.4-fpm state=restarted

- name: restart php8.0-fpm
  service: name=php8.0-fpm state=restarted

- name: restart php-fpm
  shell: >
    set -eu -o pipefail;
    for SRV in $(dpkg --list |grep php|grep fpm |awk '{print $2}'); do
      (set -x && systemctl restart $SRV);
    done
  args:
    executable: /bin/bash
