---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Ensure dirmngr is installed (gnupg dependency).
      apt:
        name: dirmngr
        state: present

    - name: Add repository for PHP
      apt_repository: repo='ppa:ondrej/php'

  roles:
    - role: ansible-role-php

  vars:
    php_default_version: 7.3
    php_versions:
      - 7.3
