---
- name: Converge
  hosts: all
  become: true

  vars:
    php_default_version: '7.0'

  roles:
    - role: ansible-role-php

  tasks:

  post_tasks:
    - name: Confirm PHP version is correct.
      shell: php -v | grep -F '{{ php_default_version }}'
      changed_when: false

