---
- name: Prepare
  hosts: all
  become: true

  vars_files: ./vars.yml

  tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Ensure dirmngr is installed (gnupg dependency).
      apt:
        name: dirmngr
        state: present
