---
- name: Check php is configured
  hosts: all
  become: yes

  tasks:
    - name: Confirm PHP configuration is correct.
      shell: php -v | grep '7.1'
      changed_when: false

    - name: Confirm PHP configuration is correct.
      shell: php -i | grep 'memory_limit.*256'
      changed_when: false
