---
- name: Check that nginx file has been created
  hosts: all
  become: yes

  tasks:
    - name: Confirm PHP configuration is correct.
      shell: php -i | grep 'memory_limit.*192'
      changed_when: false
