---
on:
 # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - php7.4
          - php8.0
          - default   # aka php81modern. Only uses 8.1 style lists for all php versions.
          - php81legacy  # Mixes new 8.1 style list and keeps pre-8.1 module lists.
        image:
          - registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:jammy
          - registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:focal
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          options: parallel
          scenario: "${{ matrix.scenario }}"
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.image }}"
