---
'on':
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - php7.4
          - php8.0
          # PHP 8.1 and beyond; uses 8.1-style lists for all PHP versions.
          - default
          # Mixes new 8.1-style lists with pre-8.1 module lists.
          - php81legacy
        image:
          - geerlingguy/docker-ubuntu2604-ansible:latest
          - geerlingguy/docker-ubuntu2404-ansible:latest
          - geerlingguy/docker-ubuntu2204-ansible:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          options: parallel
          scenario: "${{ matrix.scenario }}"
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.image }}"
