---
'on':
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  # @TODO: Lint is badly out of date. Needs fixing.
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #     - name: Run ansible-lint
  #       uses: ansible/ansible-lint@main
  test:
    # needs:
    #   - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - geerlingguy/docker-ubuntu2604-ansible:latest
          - geerlingguy/docker-ubuntu2404-ansible:latest
          - geerlingguy/docker-ubuntu2204-ansible:latest
        php_version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          options: parallel
          scenario: default
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.image }}"
          MOLECULE_PHP_VERSION: "${{ matrix.php_version }}"
